/**
 * fal.ai image-to-video client.
 *
 * The fal queue API gives us a simple submit + status + result flow:
 *
 *   1. `fal.queue.submit(endpoint, { input })`        → returns request_id
 *   2. `fal.queue.status(endpoint, { requestId })`    → IN_QUEUE | IN_PROGRESS | COMPLETED
 *   3. `fal.queue.result(endpoint, { requestId })`    → { data: { video: { url } } }
 *
 * Persisting `(endpoint, requestId)` on the row means the status route can
 * re-derive everything it needs from Supabase without holding any in-memory
 * state across requests. Caller-side polling — same as the previous
 * Higgsfield iteration.
 *
 * This module deliberately stays "dumb" about per-model input schemas: the
 * caller (src/lib/video.ts) hands us a fully-shaped `body` and we just hand
 * it to fal. Each fal video endpoint has its own input keys (Seedance uses
 * `image_url`, Kling uses `start_image_url`, neither accepts the other's
 * resolution / aspect / audio knobs) — letting the model registry shape the
 * body avoids us silently sending invalid keys that fal queues but then
 * 422s on result fetch.
 */

import { fal } from "@fal-ai/client";
import { env } from "@/lib/env";

let configured = false;
function ensureConfigured() {
  if (configured) return;
  fal.config({ credentials: env.fal.key() });
  configured = true;
}

// -----------------------------------------------------------------------------
// Types
// -----------------------------------------------------------------------------

export type FalVideoStatus = "queued" | "running" | "completed" | "failed";

export type FalVideoSubmitInput = {
  endpoint: string;
  // Already shaped to match the endpoint's input schema by the caller. We
  // don't assume keys like `image_url` exist; we just forward.
  body: Record<string, unknown>;
};

export type FalVideoSubmission = {
  requestId: string;
};

export type FalVideoStatusResult = {
  status: FalVideoStatus;
  videoUrl?: string;
  error?: string;
};

// -----------------------------------------------------------------------------
// Submit
// -----------------------------------------------------------------------------

export async function submitFalVideo(
  input: FalVideoSubmitInput,
): Promise<FalVideoSubmission> {
  ensureConfigured();

  console.log(
    `[fal-video] submit ${input.endpoint} body_keys=${Object.keys(input.body).join(",")}`,
  );
  try {
    const { request_id } = await fal.queue.submit(input.endpoint, {
      input: input.body,
    });
    console.log(
      `[fal-video] ${input.endpoint} submitted — request_id=${request_id}`,
    );
    return { requestId: request_id };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[fal-video] submit ${input.endpoint} failed: ${msg}`);
    throw new Error(`fal video submit failed: ${msg}`);
  }
}

// -----------------------------------------------------------------------------
// One-shot status check — the caller (the /api/video/[id]/status route) drives
// its own polling cadence. We never block here; if the job is still queued or
// running we just return that.
// -----------------------------------------------------------------------------

interface RawQueueStatus {
  status?: string;
  logs?: { message?: string; level?: string }[];
}

export async function checkFalVideoStatus(
  endpoint: string,
  requestId: string,
): Promise<FalVideoStatusResult> {
  ensureConfigured();

  let status: RawQueueStatus;
  try {
    // Pull logs so that when fal's queue marks a job as COMPLETED-with-error
    // (or surfaces a non-standard status), we can lift the actual error
    // message instead of returning an opaque "Unprocessable Entity" later.
    status = (await fal.queue.status(endpoint, {
      requestId,
      logs: true,
    })) as RawQueueStatus;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    // Most likely a stale/unknown request id (e.g. a row generated by the
    // legacy Higgsfield code, or a request that fal expired). Surface as a
    // hard failure so the row gets flipped to "failed" and the user can
    // delete + retry instead of polling forever.
    return { status: "failed", error: msg };
  }

  switch (status.status) {
    case "COMPLETED":
      return finaliseCompleted(endpoint, requestId, status);
    case "IN_PROGRESS":
      return { status: "running" };
    case "IN_QUEUE":
      return { status: "queued" };
    case undefined:
    case null:
      return { status: "running" };
    default:
      return {
        status: "failed",
        error: summariseFailure(status) ?? `Unexpected fal status: ${status.status}`,
      };
  }
}

interface FalQueueResultEnvelope {
  data: {
    video?: { url?: string };
    // Some endpoints (older fal LoRA video models) put output under different
    // keys — we read both to be robust.
    output?: { video?: { url?: string } };
    file?: { url?: string };
  };
}

async function finaliseCompleted(
  endpoint: string,
  requestId: string,
  statusEnvelope: RawQueueStatus,
): Promise<FalVideoStatusResult> {
  try {
    const result = (await fal.queue.result(endpoint, {
      requestId,
    })) as FalQueueResultEnvelope;
    const videoUrl =
      result.data?.video?.url ??
      result.data?.output?.video?.url ??
      result.data?.file?.url;
    if (!videoUrl) {
      return {
        status: "failed",
        error:
          summariseFailure(statusEnvelope) ??
          "fal reported COMPLETED but no video URL was attached.",
      };
    }
    return { status: "completed", videoUrl };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    // "Unprocessable Entity" / 422 from fal.queue.result means the job ran
    // but the validator rejected something about the inputs (we've seen this
    // happen when an endpoint silently ignores unknown body keys at submit
    // time but then errors on result). The status logs usually contain a
    // human-readable reason — surface it so the gallery shows something
    // actionable like "field required: start_image_url".
    const detail = summariseFailure(statusEnvelope);
    return {
      status: "failed",
      error: detail ? `${detail} (${msg})` : `fal result fetch failed: ${msg}`,
    };
  }
}

/** Pluck the most useful error line out of a fal queue status envelope. */
function summariseFailure(s: RawQueueStatus): string | null {
  if (!s.logs || s.logs.length === 0) return null;
  // Walk from the end — the failure line is usually last.
  for (let i = s.logs.length - 1; i >= 0; i--) {
    const log = s.logs[i];
    if (!log?.message) continue;
    const isErr =
      log.level === "ERROR" ||
      log.level === "error" ||
      /error|fail|invalid|unprocessable|required|missing/i.test(log.message);
    if (isErr) {
      // Cap so we don't dump multi-KB stack traces into the gallery.
      return log.message.slice(0, 300);
    }
  }
  return null;
}
